In [ ]:
import requests
import pandas as pd

api_key = "#####"  # kendi API anahtarını buraya yaz

movies = []

for page in range(1, 6):  # ilk 5 sayfa (100 film)
    url = (
        f"https://api.themoviedb.org/3/discover/movie"
        f"?api_key={api_key}"
        f"&with_watch_providers=8"
        f"&watch_region=TR"
        f"&sort_by=popularity.desc"
        f"&page={page}"
    )
    res = requests.get(url).json()
    for m in res['results']:
        movies.append({
            "Title": m['title'],
            "Rating": m['vote_average'],
            "Release Date": m['release_date'],
            "Overview": m['overview']
        })

df_movies = pd.DataFrame(movies)
df_movies.to_csv("netflix_movies.csv", index=False)

In [3]:
df_movies

,Title,Rating,Release Date,Overview
0,Last Bullet,6.854,2025-05-06,Car genius Lino returns to conclude his vendet...
1,Exterritorial,6.700,2025-04-29,"When her son vanishes inside a US consulate, e..."
2,Bad Influence,5.700,2025-01-24,An ex-con gets a fresh start when hired to pro...
3,Havoc,6.539,2025-04-25,When a drug heist swerves lethally out of cont...
4,Jewel Thief: The Heist Begins,6.684,2025-04-25,"In this high-octane battle of wits and wills, ..."
...,...,...,...,...
95,Carry-On,6.909,2024-12-05,An airport security officer races to outsmart ...
96,Ted 2,6.313,2015-06-25,Newlywed couple Ted and Tami-Lynn want to have...
97,Howl's Moving Castle,8.397,2004-09-09,"Sophie, a young milliner, is turned into an el..."
98,The Mummy,6.900,1999-04-16,Dashing legionnaire Rick O'Connell stumbles up...
99,Call Me by Your Name,8.100,2017-07-28,"In 1980s Italy, a relationship begins between ..."

In [5]:
tv_shows = []

for page in range(1, 6):  # ilk 5 sayfa (100 dizi)
    url = (
        f"https://api.themoviedb.org/3/discover/tv"
        f"?api_key={api_key}"
        f"&with_watch_providers=8"
        f"&watch_region=TR"
        f"&sort_by=popularity.desc"
        f"&page={page}"
    )
    res = requests.get(url).json()
    for s in res['results']:
        tv_shows.append({
            "Title": s['name'],
            "Rating": s['vote_average'],
            "First Air Date": s['first_air_date'],
            "Overview": s['overview']
        })

df_tv = pd.DataFrame(tv_shows)
df_tv.to_csv("netflix_tv_shows.csv", index=False)

In [7]:
df_tv

,Title,Rating,First Air Date,Overview
0,The Eternaut,7.813,2025-04-30,After a devastating toxic snowfall kills milli...
1,Miraculous: Tales of Ladybug & Cat Noir,8.000,2015-10-19,"Marinette and Adrien, two Parisian teenagers, ..."
2,Ninjago: Masters of Spinjitzu,7.895,2012-01-11,"When the fate of their world, Ninjago, is chal..."
3,The Blacklist,7.638,2013-09-23,"Raymond ""Red"" Reddington, one of the FBI's mos..."
4,Keeping Up with the Kardashians,7.400,2007-10-14,A peek inside the exploits and privileged priv...
...,...,...,...,...
95,The Good Place,7.965,2016-09-19,"Eleanor Shellstrop, an ordinary woman who, thr..."
96,Blood of Zeus,7.791,2020-10-27,In a brewing war between the gods of Olympus a...
97,Manifest,7.654,2018-09-24,After landing from a turbulent but routine fli...
98,Yu Yu Hakusho,8.500,1992-10-10,"One day, 14-year-old Yusuke Urameshi suddenly ..."
99,Pororo the Little Penguin,6.750,2003-11-27,Fun adventures await in the forest named Poron...